### ISSUE TITLE
discord key file token error

### ISSUE THREAD

**Issue by screwyluie** [etotheipi/sdxl_discord_bot#1]
added the token to ~/.sdxlbot file as token:string but I'm getting the following:

`Traceback (most recent call last):
  File "/home/screwyluie/projects/sdxl_discord_bot/sdxl_bot.py", line 455, in <module>
    sdxl_bot = SdxlBot(args)
  File "/home/screwyluie/projects/sdxl_discord_bot/sdxl_bot.py", line 65, in __init__
    self.discord_token = discord_key_file['token']
TypeError: string indices must be integers`

could use some help.

**Comment by screwyluie** [comment]
nevermind, missed the space, it's token: string
